name: Regression
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - oracle-ads>=2.9.0
      - report-creator
      - cerberus
      - scikit-learn
      - shap
      - xgboost
