blank_issues_enabled: false
contact_links:
  - name: Check the docs
    url: https://accelerated-data-science.readthedocs.io/en/latest/
    about: If you need help with your first steps with oracle-ads please check the docs.
  - name: Security vulnerabilities
    url: https://www.oracle.com/corporate/security-practices/assurance/vulnerability/reporting.html
    about: How to report security vulnerabilities to Oracle.