name: Feature Request
description: Feature and enhancement proposals in oracle-ads library
title: "[FR]: "
labels: [Task, Backlog]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Before proceeding, please review the [Contributing to this repository](https://github.com/oracle/accelerated-data-science/blob/main/CONTRIBUTING.md) and the [Code of Conduct](https://github.com/oracle/.github/blob/main/CODE_OF_CONDUCT.md).
        
        ---
        
        Thank you for submitting a feature request.
  - type: dropdown
    id: contribution
    attributes:
      label: Willingness to contribute
      description: Would you or another member of your organization be willing to contribute an implementation of this feature?
      options:
        - Yes. I can contribute this feature independently.
        - Yes. I would be willing to contribute this feature with guidance from the oracle-ads team.
        - No. I cannot contribute this feature at this time.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal Summary
      description: |
        In a few sentences, provide a clear, high-level description of the feature request
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: |
        - What is the use case for this feature?
        - Why is this use case valuable to support for OCI DataScience users in general?
        - Why is this use case valuable to support for your project(s) or organization?
        - Why is it currently difficult to achieve this use case?
      value: |
        > #### What is the use case for this feature?

        > #### Why is this use case valuable to support for OCI DataScience users in general?

        > #### Why is this use case valuable to support for your project(s) or organization?

        > #### Why is it currently difficult to achieve this use case?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: |
        Use this section to include any additional information about the feature. If you have a proposal for how to implement this feature, please include it here. For implementation guidelines, please refer to the [Contributing to this repository](https://github.com/oracle/accelerated-data-science/blob/main/CONTRIBUTING.md).
    validations:
      required: false
