#!/bin/bash

for file in $DATASCIENCE_INSTALL_DIR/pre-run-ds/*.sh; do
    [ -f "$file" ] && [ -x "$file" ] && "$file"
done

for file in $DATASCIENCE_INSTALL_DIR/pre-run-user/*.sh; do
    [ -f "$file" ] && [ -x "$file" ] && "$file"
done

JUPYTER_STOP_COMMAND="jupyter notebook stop"

echo "Jupyter Lab command: $JUPYTER_EXEC_COMMAND"
exec $JUPYTER_EXEC_COMMAND