name: "Macaron GitHub Actions Security"

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  push:
    branches: [main]
    paths:
      - ".github/workflows/**"
      - ".github/actions/**"
  schedule:
    - cron: "17 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check-github-actions:
    name: "check-github-actions"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: "Run Macaron"
        uses: oracle/macaron@4ddb55e3c9ef2c77b548be55c557078c4476fd9c # v0.24.0
        with:
          repo_path: ./
          policy_file: check-github-actions
          policy_purl: "pkg:github.com/oracle/accelerated-data-science@.*"
          output_dir: macaron-output
          reports_retention_days: 90
