name: "[DO NOT TRIGGER] Publish to PyPI"

# To run this workflow manually from the Actions tab
on: workflow_dispatch

permissions:
  contents: read

jobs:
  build-n-publish:
    name: Build and publish Python 🐍 distribution 📦 to PyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.x"
      - name: Build distribution 📦
        run: |
          pip install build
          make dist
      - name: Validate
        run: |
          pip install dist/*.whl
          python -c "import ads;"
## To run publish to test PyPI a secret with token needs to be added,
##    this one GH_ADS_TESTPYPI_TOKEN - removed after initial test.
## Project name also needed to be updated in pyproject.toml - name = "test_oracle_ads" in [project] section
##    regular name is occupied by former developer and can't be used for testing
#      - name: Publish distribution 📦 to Test PyPI
#        env:
#          TWINE_USERNAME: __token__
#          TWINE_PASSWORD: ${{ secrets.GH_ADS_TESTPYPI_TOKEN }}
#        run: |
#          pip install twine
#          twine upload -r testpypi dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD
      - name: Publish distribution 📦 to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.GH_ADS_PYPI_TOKEN }}
        run: |
          pip install twine
          twine upload dist/* -u $TWINE_USERNAME -p $TWINE_PASSWORD
