name: "[Py3.9-3.13] - Default Tests"

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**"
      - "ads/**"
      - "!ads/opctl/operator/**"
      - "pyproject.toml"


# Cancel in progress workflows on pull_requests.
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

# hack for https://github.com/actions/cache/issues/810#issuecomment-1222550359
env:
  SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5

jobs:
  test:
    name: python ${{ matrix.python-version }}, default_setup
    runs-on: ubuntu-latest
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
          cache-dependency-path: |
            pyproject.toml
            "**requirements.txt"

      - uses: ./.github/workflows/set-dummy-conf
        name: "Test config setup"

      - name: "Run default_setup tests folder ONLY with minimum ADS dependencies"
        timeout-minutes: 30
        shell: bash
        env:
          NoDependency: True
        run: |
          set -x # print commands that are executed
          $CONDA/bin/conda init
          source /home/runner/.bashrc
          conda install python=${{ matrix.python-version }}
          pip install -r test-requirements.txt
          conda list
          python -m pytest -v -p no:warnings --durations=5 tests/unitary/default_setup
